# Generated by Django 3.2.18 on 2023-04-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230426_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
