# Generated by Django 3.2.18 on 2023-04-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_scan_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='seen_by_patient',
            field=models.BooleanField(default=False),
        ),
    ]
