# Generated by Django 3.2.18 on 2023-05-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_scan_seen_by_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalfolder',
            name='nationality',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='medicalfolder',
            name='service',
            field=models.CharField(default='', max_length=240),
        ),
    ]
