# Generated by Django 3.2.18 on 2023-05-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230501_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalfolder',
            name='analysis',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='medicalfolder',
            name='birth_date',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='medicalfolder',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='medicalfolder',
            name='folderNumber',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='medicalfolder',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='medicalfolder',
            name='medical_cover',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='medicalfolder',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='medicalfolder',
            name='patient',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='medicalfolder',
            name='practitioner_doctor',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='medicalfolder',
            name='service',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='medicalfolder',
            name='status_report',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
