# Generated by Django 3.2.18 on 2023-05-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230505_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfolder',
            name='autre',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='medicalfolder',
            name='maladie_Poumon',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='medicalfolder',
            name='maladie_coronariennes',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='medicalfolder',
            name='maladie_cérébrales',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='medicalfolder',
            name='maladie_fois',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
    ]
