# Generated by Django 3.2.18 on 2023-05-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230510_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfolder',
            name='allergie',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='medicalfolder',
            name='maladiechronique',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
    ]
